version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "sebastienrousseau"
    labels:
      - 'Type: Maintenance'
      - 'Target: GitHub Actions'
