#
# ____  _        _      _              _        ____  _         _
#/ ___|| | _____| | ___| |_ ___  _ __ (_) ___  / ___|| |_ _   _| |_   _ ___
#\___ \| |/ / _ \ |/ _ \ __/ _ \| '_ \| |/ __| \___ \| __| | | | | | | / __|
# ___) |   <  __/ |  __/ || (_) | | | | | (__   ___) | |_| |_| | | |_| \__ \
#|____/|_|\_\___|_|\___|\__\___/|_| |_|_|\___| |____/ \__|\__, |_|\__,_|___/
#                                                         |___/
# Skeletonic Stylus Library
# https://skeletonicstylus.com/
#
# Copyright (c) Sebastien Rousseau 2022. All rights reserved
# Licensed under the MIT license
#

name: Skeletonic Stylus Release

on:
  release:
    types: [ created ]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.24.2
      - run: pnpm i
      - run: pnpm test
    env:
      CI: true

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: sebastienrousseau
      - run: pnpm ci
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set package registry
        run: pnpm config set registry https://npm.pkg.github.com
      - name: GitHub package registry authentication
        run: pnpm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - name: Npm registry authentication
        run: pnpm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish the package to GitHub and Npm package registries
        run: pnpm publish --access=public
