#
# ____  _        _      _              _        ____  _         _
#/ ___|| | _____| | ___| |_ ___  _ __ (_) ___  / ___|| |_ _   _| |_   _ ___
#\___ \| |/ / _ \ |/ _ \ __/ _ \| '_ \| |/ __| \___ \| __| | | | | | | / __|
# ___) |   <  __/ |  __/ || (_) | | | | | (__   ___) | |_| |_| | | |_| \__ \
#|____/|_|\_\___|_|\___|\__\___/|_| |_|_|\___| |____/ \__|\__, |_|\__,_|___/
#                                                         |___/
# Skeletonic Stylus Library
# https://skeletonicstylus.com/
#
# Copyright (c) Sebastien Rousseau 2021. All rights reserved
# Licensed under the MIT license
#

name: NPM Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
        name: Build
      - run: npm test --if-present
        env:
          CI: true

  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Publish npm package
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to npmjs
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
